spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379

server:
  port: 8083

zuul:
  sensitive-headers: 
  routes:
#    order: /myOrder/**
#    product: /myProduct/**
    myOrder:
        # /myOrder/** -> /order/**
        path: /myOrder/**
        serviceId: order
        # sensitiveHeaders:
    myProduct:
      path: /myProduct/**
      serviceId: product
      # sensitiveHeaders:
#   ignored-patterns:
#     - /**/product/list

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
env: dev
