spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/haiyusun/springcloud-config.git
          username: haiyusun
          password: Shy13259461696
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
